# Generated by Django 5.1.2 on 2024-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=10)),
                ('aliasName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=6)),
                ('endDate', models.CharField(max_length=10)),
                ('startDate', models.CharField(max_length=10)),
                ('fiscalYear', models.CharField(max_length=4)),
                ('fiscalPeriod', models.CharField(max_length=2)),
                ('accn', models.CharField(max_length=20)),
                ('grossProfit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('revenues', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('netIncomeLoss', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('assetsCurrent', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('liabilitiesCurrent', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('inventoryNet', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('costOfGoodsAndServicesSold', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('totalLiabilities', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('stockholdersEquity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('weightedAverageNumberOfSharesOutstandingBasic', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('currentSharePrice', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
